/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.github.jvalentino.jenkins

import com.github.jvalentino.jenkins.service.JobListingService
import groovy.transform.CompileDynamic
import groovy.util.logging.Slf4j
import com.github.jvalentino.jenkins.util.HttpUtil

/**
 * The main application entry point
 * @author john.valentino
 */
@CompileDynamic
@Slf4j
class App {

    String greeting = 'Hello World!'

    protected JobListingService jobListingService = new JobListingService();

    static void main(String[] args) {
        new App().execute()
    }

    void execute() {
        AppSettings settings = this.loadAppSettings()

        List jobs = jobListingService.fetch(settings)
        log.info("${jobs.size()} jobs found")

        jobListingService.submitToNewRelic(settings, jobs)
    }

    protected AppSettings loadAppSettings() {
        Properties properties = System.properties
        AppSettings result = new AppSettings()
        result.with {
            jenkinsUsername = properties.get('JENKINS_USERNAME')
            jenkinsToken = properties.get('JENKINS_TOKEN')
            jenkinsUrl = properties.get('JENKINS_URL')
            newRelicAccountId = properties.get('NEW_RELIC_ACCOUNT_ID')
            newRelicKey = properties.get('NEW_RELIC_KEY')
        }
        result
    }

}
